<?php

namespace Mpk\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConvenantFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvenantFamilyRepository extends EntityRepository
{
}
